# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

a = input("Введите вид питомца: ")
b = input("Введите возраст питомца: ")
c = input("Введите кличку питомца: ")



print('Это', a, 'по кличке "',c,'". Возраст: ', b, "года.")