# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

a = input("Введите первый этап развития человека: ")
b = input("Введите второй этап развития человека: ")
c = input("Введите третий этап развития человека: ")
d = input("Введите четвертый этап развития человека: ")
e = input("Введите пятый этап развития человека: ")
f = input("Введите шестой этап развития человека: ")




print(a,b,c,d,e,f, sep="=>")